"use strict";
// Object.defineProperty(exports, "__esModule", { value: true });
// exports.US_STATES = void 0;
//    "florida-discipline"
//    "georgia-discipline"
export const STATE_DESCRIPTIONS = {
    'alabama': "Information about this state's peace officer employment history database is currently unavailable.",
    'alaska': "Information about this state's peace officer employment history database is currently unavailable.",
    'arizona': "Data about law enforcement officers in Arizona were obtained under the Arizona Public Records Law from the Arizona Peace Officer Standards and Training Board. The data released includes personnel and employment history for all officers certified by the POST, with data going back to the 1950s.",
    'arkansas': "Information about this state's peace officer employment history database is currently unavailable.",
    'california': "Data about law enforcement officers in California were obtained under the California Public Records Act from the California Commission on Peace Officer Standards and Training and the California Department of Corrections and Rehabilitation.",
    'colorado': "Information about this state's peace officer employment history database is currently unavailable.",
    'connecticut': "Information about this state's peace officer employment history database is currently unavailable.",
    'delaware': "Information about this state's peace officer employment history database is currently unavailable.",
    'columbia': "Information about this state's peace officer employment history database is currently unavailable.",
    'florida': "Data about law enforcement officers in Florida were obtained under the Florida Sunshine Law from the Florida Department of Law Enforcement. The data released includes personnel information, certification information, employment history, complaints and disciplinary actions for all officers certified in the state, with data going back to the 1940s.",
    'florida-discipline': "This table shows sustained allegations of misconduct by Florida law enforcement officers, as reported to the Florida Department of Law Enforcement and released under the Florida Sunshine Law.",
    'georgia': "Data about law enforcement officers in Georgia were obtained under the Georgia Open Records Act from the Georgia Peace Officer Standards & Training Council. The dataset includes information on all certified peace and corrections officers, with work history data dating back to the early 1990s.",
    'georgia-discipline': "This table shows arrests and sustained allegations of misconduct by Georgia law enforcement officers, as reported to the Georgia Peace Officer Standards & Training Council and released under the Georgia Open Records Act.",
    'hawaii': "Information about this state's peace officer employment history database is currently unavailable.",
    'idaho': "Data about law enforcement officers in Idaho were obtained under the Idaho Public Records Law from the Idaho Peace Officer Standards and Training. The data released includes personnel and employment history for officers certified by the POST.",
    'illinois': "Data about law enforcement in Illinois were obtained under the Illinois Freedom of Information Act from the Illinois Law Enforcement Training and Standards Board. The data released includes personnel information, license and certification information, and employment history for all officers certified in the state, with data going back to the 1960s.",
    'indiana': "Data about law enforcement in Indiana were obtained under the Indiana Access to Public Records Act from the Indiana Law Enforcement Academy. The data released includes personnel and employment history for all officers certified by the ILEA, with data going back to the 1970s.",
    'iowa': "Information about this state's peace officer employment history database is currently unavailable.",
    'kansas': "Data about law enforcement in Kansas were obtained under the Kansas Open Records Act from the Kansas Commission on Peace Officers' Standards and Training. The data released includes personnel and employment history for all officers certified by CPOST.",
    'kentucky': "Data about law enforcement in Kentucky were obtained under the Kentucky Open Records Act from the Kentucky Law Enforcement Council.",
    'louisiana': "Information about this state's peace officer employment history database is currently unavailable.",
    'maine': "Information about this state's peace officer employment history database is currently unavailable.",
    'maryland': "Data about law enforcement in Maryland were obtained under the Maryland Public Information Act from the Maryland Department of Public Safety and Correctional Services. The data released includes personnel information and employment history for all officers certified in the state, with data going back to the 1960s.",
    'massachusetts': "Information about this state's peace officer employment history database is currently unavailable.",
    'michigan': "Information about this state's peace officer employment history database is currently unavailable.",
    'minnesota': "Information about this state's peace officer employment history database is currently unavailable.",
    'mississippi': "Information about this state's peace officer employment history database is currently unavailable.",
    'missouri': "Information about this state's peace officer employment history database is currently unavailable.",
    'montana': "Information about this state's peace officer employment history database is currently unavailable.",
    'nebraska': "Information about this state's peace officer employment history database is currently unavailable.",
    'nevada': "Information about this state's peace officer employment history database is currently unavailable.",
    'new-hampshire': "Information about this state's peace officer employment history database is currently unavailable.",
    'new-jersey': "Information about this state's peace officer employment history database is currently unavailable.",
    'new-mexico': "Data about law enforcement in New Mexico were obtained under the New Mexico Inspection of Public Records Act from the New Mexico Law Enforcement Agency. The data released includes personnel and employment history for all officers certified by NMLEA's Law Enforcement Certification Board and its predecessor, with data going back to the 1960s.",
    'new-york': "Information about this state's peace officer employment history database is currently unavailable.",
    'north-carolina': "Data about law enforcement in North Carolina were obtained under the North Carolina Public Records Act from the North Carolina Department of Justice. The data released includes personnel and employment history for all officers certified by NCDOJ's Criminal Justice Education & Training Standards Commission and Sheriffs' Education & Training Standards Commission, with data going back to the 1970s.",
    'north-dakota': "Information about this state's peace officer employment history database is currently unavailable.",
    'ohio': "Data about law enforcement in Ohio were obtained under the Ohio Public Records Act from the Ohio Peace Officer Training Commission. The data released includes personnel and employment history for all officers certified in the state, with data going back to the 1950s.",
    'oklahoma': "Information about this state's peace officer employment history database is currently unavailable.",
    'oregon': "Data about law enforcement in Oregon were obtained under the Oregon Public Records Law from the Oregon Department of Public Safety Standards and Training. The data released includes certified police officers, corrections officers, and parole/probation officers with work history data going back into the 1970s.",
    'pennsylvania': "Information about this state's peace officer employment history database is currently unavailable.",
    'rhode-island': "Information about this state's peace officer employment history database is currently unavailable.",
    'south-carolina': "Data about law enforcement in South Carolina were obtained under the South Carolina Freedom of Information Act from the South Carolina Criminal Justice Academy. The data released includes certified police officers, corrections officers, and parole/probation officers with work history data going back into the 1970s.",
    'south-dakota': "Information about this state's peace officer employment history database is currently unavailable.",
    'tennessee': "Data about law enforcement in Tennessee were obtained under the Tennessee Public Records Act from the Tennessee Peace Officer Standards & Training Commission. The dataset includes information on all certified peace and corrections officers, with work history data dating back to the mid 1980s.",
    'texas': "Data about law enforcement in Texas were obtained under the Texas Public Information Act from the Texas Commission on Law Enforcement. The data released includes certification information and employment history for all officers certified in the state, with data going back to the 1930s.",
    'utah': "Data about law enforcement in Utah were obtained under the Utah Government Records Access and Management Act from Utah Peace Officer Standards and Training.",
    'vermont': "Data about law enforcement in Vermont were obtained under the Vermont Public Records Law from the Vermont Criminal Justice Council. The data released includes certification information and employment history for all certified police officers, with work history data going back into the late 1970s.",
    'virginia': "Information about this state's peace officer employment history database is currently unavailable.",
    'washington': "Data about law enforcement in Washington were obtained under the Washington Public Records Act from the Washington Criminal Justice Training Commission. The data released includes certification information and employment history for all certified police officers, with work history data going back into the late 1970s.",
    'west-virginia': "Data about law enforcement in West Virginia were obtained under the West Virginia Freedom of Information Act from the West Virginia Law Enforcement Professional Standards Program.",
    'wyoming': "Data about law enforcement in Wyoming were obtained under the Wyoming Public Records Act from the Wyoming Peace Officer Standards and Training Commission. The data were originally obtained by WyoFile and Invisible Institute.",
};

export const US_STATES = [
    { name: 'Alabama', reference: 'alabama', abbreviation: 'AL', hasData: false, key: 'a38', dataFlag: 'no_data_lb', url: 'https://www.al.com/news/2024/09/police-employment-history-is-usually-a-public-record-in-alabama-its-a-state-secret.html' },
    { name: 'Alaska', reference: 'alaska', abbreviation: 'AK', hasData: false, key: 'a47', dataFlag: 'coming_soon' },
    { name: 'Arizona', reference: 'arizona', abbreviation: 'AZ', hasData: true, key: 'a27', dataFlag: 'full' },
    { name: 'Arkansas', reference: 'arkansas', abbreviation: 'AR', hasData: false, key: 'a30', dataFlag: 'no_data_lb', url: 'https://arkansasadvocate.com/2023/11/27/arkansas-declines-to-release-police-officer-database-preventing-public-oversight-of-problem-cops/' },
    { name: 'California', reference: 'california', abbreviation: 'CA', hasData: true, key: 'a17', dataFlag: 'full' },
    { name: 'Colorado', reference: 'colorado', abbreviation: 'CO', hasData: false, key: 'a19', dataFlag: 'no_data_lb', url: 'https://coloradofoic.org/even-with-new-post-database-and-reforms-colorado-is-in-the-minority-of-states-keeping-comprehensive-police-officer-data-secret/' },
    { name: 'Connecticut', reference: 'connecticut', abbreviation: 'CT', hasData: false, key: 'a16', dataFlag: 'no_data_tb' },
    { name: 'Delaware', reference: 'delaware', abbreviation: 'DE', hasData: false, key: 'a26', dataFlag: 'no_data_lb', url: 'https://delawarecall.com/2024/03/14/delaware-opened-up-access-to-some-police-misconduct-records-but-still-denies-requests-for-basic-police-data/' },
    { name: 'District of Columbia', reference: 'columbia', abbreviation: 'DC', hasData: false, key: 'a34', dataFlag: 'coming_soon' },
    { name: 'Florida', reference: 'florida', abbreviation: 'FL', hasData: true, key: 'a50', dataFlag: 'full' },
    { name: 'Florida Discipline', reference: 'florida-discipline', abbreviation: 'FLD', hasData: true, key: 'a50d', dataFlag: 'full' },
    { name: 'Georgia', reference: 'georgia', abbreviation: 'GA', hasData: true, key: 'a39', dataFlag: 'full' },
    { name: 'Georgia Discipline', reference: 'georgia-discipline', abbreviation: 'GAD', hasData: true, key: 'a39d', dataFlag: 'full' },
    { name: 'Hawaii', reference: 'hawaii', abbreviation: 'HI', hasData: false, key: 'a48', dataFlag: 'coming_soon' },
    { name: 'Idaho', reference: 'idaho', abbreviation: 'ID', hasData: true, key: 'a1', dataFlag: 'full' },
    { name: 'Illinois', reference: 'illinois', abbreviation: 'IL', hasData: true, key: 'a5', dataFlag: 'full' },
    { name: 'Indiana', reference: 'indiana', abbreviation: 'IN', hasData: true, key: 'a12', dataFlag: 'full' },
    { name: 'Iowa', reference: 'iowa', abbreviation: 'IA', hasData: false, key: 'a11', dataFlag: 'coming_soon' },
    { name: 'Kansas', reference: 'kansas', abbreviation: 'KS', hasData: true, key: 'a29', dataFlag: 'full' },
    { name: 'Kentucky', reference: 'kentucky', abbreviation: 'KY', hasData: true, key: 'a22', dataFlag: 'full' },
    { name: 'Louisiana', reference: 'louisiana', abbreviation: 'LA', hasData: false, key: 'a36', dataFlag: 'some_data', url: 'https://llead.co/' },
    { name: 'Maine', reference: 'maine', abbreviation: 'ME', hasData: false, key: 'a45', dataFlag: 'no_data_tb' },
    { name: 'Maryland', reference: 'maryland', abbreviation: 'MD', hasData: true, key: 'a25', dataFlag: 'full' },
    { name: 'Massachusetts', reference: 'massachusetts', abbreviation: 'MA', hasData: false, key: 'a41', dataFlag: 'no_data_tb' },
    { name: 'Michigan', reference: 'michigan', abbreviation: 'MI', hasData: false, key: 'a6', dataFlag: 'no_data_lb', url: 'https://www.metrotimes.com/news/police-transparency-expands-with-new-national-database-but-michigan-blocks-officer-data-37384703' },
    { name: 'Minnesota', reference: 'minnesota', abbreviation: 'MN', hasData: true, key: 'a4', dataFlag: 'full' },
    { name: 'Mississippi', reference: 'mississippi', abbreviation: 'MS', hasData: true, key: 'a37', dataFlag: 'full' },
    { name: 'Missouri', reference: 'missouri', abbreviation: 'MO', hasData: false, key: 'a21', dataFlag: 'no_data_lb', url: 'https://gatewayjr.org/missouri-is-home-of-police-decertification-it-also-keeps-data-showing-wandering-officers-a-secret/' },
    { name: 'Montana', reference: 'montana', abbreviation: 'MT', hasData: false, key: 'a2', dataFlag: 'no_data_lb', url: 'https://thepulp.org/montana-blocks-access-to-basic-police-data/' },
    { name: 'Nebraska', reference: 'nebraska', abbreviation: 'NE', hasData: false, key: 'a20', dataFlag: 'no_data_tb' },
    { name: 'Nevada', reference: 'nevada', abbreviation: 'NV', hasData: false, key: 'a18', dataFlag: 'no_data_lb', url: 'https://www.reviewjournal.com/investigations/agency-withholds-data-about-police-certification-employment-history-from-journalists-2881670/' },
    { name: 'New Hampshire', reference: 'new-hampshire', abbreviation: 'NH', hasData: false, key: 'a44', dataFlag: 'no_data_tb', url: 'https://newhampshirebulletin.com/2024/09/20/nh-was-tasked-with-tracking-police-employment-history-citing-cost-police-regulators-cut-it-off/' },
    { name: 'New Jersey', reference: 'new-jersey', abbreviation: 'NJ', hasData: false, key: 'a15', dataFlag: 'no_data_tb' },
    { name: 'New Mexico', reference: 'new-mexico', abbreviation: 'NM', hasData: true, key: 'a28', dataFlag: 'full' },
    { name: 'New York', reference: 'new-york', abbreviation: 'NY', hasData: false, key: 'a40', dataFlag: 'no_data_lb', url: 'https://nysfocus.com/2024/10/31/new-york-police-misconduct-employment-records' },
    { name: 'North Carolina', reference: 'north-carolina', abbreviation: 'NC', hasData: true, key: 'a32', dataFlag: 'full' },
    { name: 'North Dakota', reference: 'north-dakota', abbreviation: 'ND', hasData: false, key: 'a3', dataFlag: 'coming_soon' },
    { name: 'Ohio', reference: 'ohio', abbreviation: 'OH', hasData: true, key: 'a13', dataFlag: 'full' },
    { name: 'Oklahoma', reference: 'oklahoma', abbreviation: 'OK', hasData: false, key: 'a35', dataFlag: 'no_data_lb' },
    { name: 'Oregon', reference: 'oregon', abbreviation: 'OR', hasData: true, key: 'a7', dataFlag: 'full' },
    { name: 'Pennsylvania', reference: 'pennsylvania', abbreviation: 'PA', hasData: false, key: 'a14', dataFlag: 'no_data_lb', url: 'https://www.spotlightpa.org/news/2023/08/pennsylvania-police-officer-data-denied/' },
    { name: 'Rhode Island', reference: 'rhode-island', abbreviation: 'RI', hasData: true, key: 'a42', dataFlag: 'full' },
    { name: 'South Carolina', reference: 'south-carolina', abbreviation: 'SC', hasData: true, key: 'a33', dataFlag: 'full' },
    { name: 'South Dakota', reference: 'south-dakota', abbreviation: 'SD', hasData: false, key: 'a10', dataFlag: 'no_data_lb' },
    { name: 'Tennessee', reference: 'tennessee', abbreviation: 'TN', hasData: true, key: 'a31', dataFlag: 'full' },
    { name: 'Texas', reference: 'texas', abbreviation: 'TX', hasData: true, key: 'a49', dataFlag: 'full' },
    { name: 'Utah', reference: 'utah', abbreviation: 'UT', hasData: true, key: 'a8', dataFlag: 'full' },
    { name: 'Vermont', reference: 'vermont', abbreviation: 'VT', hasData: true, key: 'a43', dataFlag: 'full' },
    { name: 'Virginia', reference: 'virginia', abbreviation: 'VA', hasData: false, key: 'a24', dataFlag: 'no_data_lb', url: 'https://vcij.org/stories/virginia-is-in-the-minority-of-states-keeping-even-the-most-basic-police-data-secret' },
    { name: 'Washington', reference: 'washington', abbreviation: 'WA', hasData: true, key: 'a0', dataFlag: 'full' },
    { name: 'West Virginia', reference: 'west-virginia', abbreviation: 'WV', hasData: true, key: 'a23', dataFlag: 'full' },
    { name: 'Wisconsin', reference: 'wisconsin', abbreviation: 'WI', hasData: false, key: 'a46', dataFlag: 'no_data_lb', url: 'https://wisconsinexaminer.com/2024/05/24/wisconsin-is-in-the-minority-of-states-shielding-police-data-were-suing-to-change-that/' },
    { name: 'Wyoming', reference: 'wyoming', abbreviation: 'WY', hasData: true, key: 'a9', dataFlag: 'full' },
];
