export interface USState {
  name: string;
  abbreviation: string;
  hasData: boolean;
key: string;
count?: number;
}

export const US_STATES: USState[] = [
  { name: 'Alabama', abbreviation: 'AL', hasData: false, key: 'a0' },
  { name: 'Alaska', abbreviation: 'AK', hasData: false, key: 'a1' },
  { name: 'Arizona', abbreviation: 'AZ', hasData: true, key: 'a2' },
  { name: 'Arkansas', abbreviation: 'AR', hasData: false, key: 'a3' },
  { name: 'California', abbreviation: 'CA', hasData: true, key: 'a4' },
  { name: 'Colorado', abbreviation: 'CO', hasData: false, key: 'a5' },
  { name: 'Connecticut', abbreviation: 'CT', hasData: false, key: 'a6' },
  { name: 'Delaware', abbreviation: 'DE', hasData: false, key: 'a7' },
  { name: 'Florida', abbreviation: 'FL', hasData: true, key: 'a8' },
  { name: 'Georgia', abbreviation: 'GA', hasData: false, key: 'a9' },
  { name: 'Hawaii', abbreviation: 'HI', hasData: false, key: 'a10' },
  { name: 'Idaho', abbreviation: 'ID', hasData: false, key: 'a11' },
  { name: 'Illinois', abbreviation: 'IL', hasData: true, key: 'a12' },
  { name: 'Indiana', abbreviation: 'IN', hasData: false, key: 'a13' },
  { name: 'Iowa', abbreviation: 'IA', hasData: false, key: 'a14' },
  { name: 'Kansas', abbreviation: 'KS', hasData: false, key: 'a15' },
  { name: 'Kentucky', abbreviation: 'KY', hasData: false, key: 'a16' },
  { name: 'Louisiana', abbreviation: 'LA', hasData: false, key: 'a17' },
  { name: 'Maine', abbreviation: 'ME', hasData: false, key: 'a18' },
  { name: 'Maryland', abbreviation: 'MD', hasData: false, key: 'a19' },
  { name: 'Massachusetts', abbreviation: 'MA', hasData: false, key: 'a20' },
  { name: 'Michigan', abbreviation: 'MI', hasData: false, key: 'a21' },
  { name: 'Minnesota', abbreviation: 'MN', hasData: true, key: 'a22' },
  { name: 'Mississippi', abbreviation: 'MS', hasData: false, key: 'a23' },
  { name: 'Missouri', abbreviation: 'MO', hasData: false, key: 'a24' },
  { name: 'Montana', abbreviation: 'MT', hasData: false, key: 'a25' },
  { name: 'Nebraska', abbreviation: 'NE', hasData: false, key: 'a26' },
  { name: 'Nevada', abbreviation: 'NV', hasData: false, key: 'a27' },
  { name: 'New Hampshire', abbreviation: 'NH', hasData: false, key: 'a28' },
  { name: 'New Jersey', abbreviation: 'NJ', hasData: false, key: 'a29' },
  { name: 'New Mexico', abbreviation: 'NM', hasData: false, key: 'a30' },
  { name: 'New York', abbreviation: 'NY', hasData: true, key: 'a31' },
  { name: 'North Carolina', abbreviation: 'NC', hasData: false, key: 'a32' },
  { name: 'North Dakota', abbreviation: 'ND', hasData: false, key: 'a33' },
  { name: 'Ohio', abbreviation: 'OH', hasData: false, key: 'a34' },
  { name: 'Oklahoma', abbreviation: 'OK', hasData: false, key: 'a35' },
  { name: 'Oregon', abbreviation: 'OR', hasData: false, key: 'a36' },
  { name: 'Pennsylvania', abbreviation: 'PA', hasData: false, key: 'a37' },
  { name: 'Rhode Island', abbreviation: 'RI', hasData: false, key: 'a38' },
  { name: 'South Carolina', abbreviation: 'SC', hasData: false, key: 'a39' },
  { name: 'South Dakota', abbreviation: 'SD', hasData: false, key: 'a40' },
  { name: 'Tennessee', abbreviation: 'TN', hasData: false, key: 'a41' },
  { name: 'Texas', abbreviation: 'TX', hasData: true, key: 'a42' },
  { name: 'Utah', abbreviation: 'UT', hasData: false, key: 'a43' },
  { name: 'Vermont', abbreviation: 'VT', hasData: false, key: 'a44' },
  { name: 'Virginia', abbreviation: 'VA', hasData: false, key: 'a45' },
  { name: 'Washington', abbreviation: 'WA', hasData: false, key: 'a46' },
  { name: 'West Virginia', abbreviation: 'WV', hasData: false, key: 'a47' },
  { name: 'Wisconsin', abbreviation: 'WI', hasData: false, key: 'a48' },
  { name: 'Wyoming', abbreviation: 'WY', hasData: false, key: 'a49' },
];
