export interface USState {
  name: string;
  abbreviation: string;
  hasData: boolean;
key: string;
count?: number;
}

export const US_STATES: USState[] = [
  { name: 'Alabama', abbreviation: 'AL', hasData: false, key: 'a76' },
  { name: 'Alaska', abbreviation: 'AK', hasData: false, key: 'a94' },
  { name: 'Arizona', abbreviation: 'AZ', hasData: true, key: 'a54' },
  { name: 'Arkansas', abbreviation: 'AR', hasData: false, key: 'a60' },
  { name: 'California', abbreviation: 'CA', hasData: true, key: 'a34' },
  { name: 'Colorado', abbreviation: 'CO', hasData: false, key: 'a38' },
  { name: 'Connecticut', abbreviation: 'CT', hasData: false, key: 'a32' },
  { name: 'Delaware', abbreviation: 'DE', hasData: false, key: 'a52' },
  { name: 'Columbia', abbreviation: 'DC', hasData: true, key: 'a68' },
  { name: 'Florida', abbreviation: 'FL', hasData: true, key: 'a100' },
  { name: 'Georgia', abbreviation: 'GA', hasData: false, key: 'a78' },
  { name: 'Hawaii', abbreviation: 'HI', hasData: false, key: 'a96' },
  { name: 'Idaho', abbreviation: 'ID', hasData: false, key: 'a2' },
  { name: 'Illinois', abbreviation: 'IL', hasData: true, key: 'a10' },
  { name: 'Indiana', abbreviation: 'IN', hasData: false, key: 'a24' },
  { name: 'Iowa', abbreviation: 'IA', hasData: false, key: 'a22' },
  { name: 'Kansas', abbreviation: 'KS', hasData: false, key: 'a58' },
  { name: 'Kentucky', abbreviation: 'KY', hasData: false, key: 'a44' },
  { name: 'Louisiana', abbreviation: 'LA', hasData: false, key: 'a72' },
  { name: 'Maine', abbreviation: 'ME', hasData: false, key: 'a90' },
  { name: 'Maryland', abbreviation: 'MD', hasData: false, key: 'a50' },
  { name: 'Massachusetts', abbreviation: 'MA', hasData: false, key: 'a82' },
  { name: 'Michigan', abbreviation: 'MI', hasData: false, key: 'a12' },
  { name: 'Minnesota', abbreviation: 'MN', hasData: true, key: 'a8' },
  { name: 'Mississippi', abbreviation: 'MS', hasData: false, key: 'a74' },
  { name: 'Missouri', abbreviation: 'MO', hasData: false, key: 'a42' },
  { name: 'Montana', abbreviation: 'MT', hasData: false, key: 'a4' },
  { name: 'Nebraska', abbreviation: 'NE', hasData: false, key: 'a40' },
  { name: 'Nevada', abbreviation: 'NV', hasData: false, key: 'a36' },
  { name: 'New Hampshire', abbreviation: 'NH', hasData: false, key: 'a88' },
  { name: 'New Jersey', abbreviation: 'NJ', hasData: false, key: 'a30' },
  { name: 'New Mexico', abbreviation: 'NM', hasData: false, key: 'a56' },
  { name: 'New York', abbreviation: 'NY', hasData: true, key: 'a80' },
  { name: 'North Carolina', abbreviation: 'NC', hasData: false, key: 'a64' },
  { name: 'North Dakota', abbreviation: 'ND', hasData: false, key: 'a6' },
  { name: 'Ohio', abbreviation: 'OH', hasData: false, key: 'a26' },
  { name: 'Oklahoma', abbreviation: 'OK', hasData: false, key: 'a70' },
  { name: 'Oregon', abbreviation: 'OR', hasData: false, key: 'a14' },
  { name: 'Pennsylvania', abbreviation: 'PA', hasData: false, key: 'a28' },
  { name: 'Rhode Island', abbreviation: 'RI', hasData: false, key: 'a84' },
  { name: 'South Carolina', abbreviation: 'SC', hasData: false, key: 'a66' },
  { name: 'South Dakota', abbreviation: 'SD', hasData: false, key: 'a20' },
  { name: 'Tennessee', abbreviation: 'TN', hasData: false, key: 'a62' },
  { name: 'Texas', abbreviation: 'TX', hasData: true, key: 'a98' },
  { name: 'Utah', abbreviation: 'UT', hasData: false, key: 'a16' },
  { name: 'Vermont', abbreviation: 'VT', hasData: false, key: 'a86' },
  { name: 'Virginia', abbreviation: 'VA', hasData: false, key: 'a48' },
  { name: 'Washington', abbreviation: 'WA', hasData: false, key: 'a0' },
  { name: 'West Virginia', abbreviation: 'WV', hasData: false, key: 'a46' },
  { name: 'Wisconsin', abbreviation: 'WI', hasData: false, key: 'a92' },
  { name: 'Wyoming', abbreviation: 'WY', hasData: false, key: 'a18' },
];
